### ISSUE TITLE
"this hpp implements the merge of (relation R1 and R2) in ESORICS 2015" is which article?

### ISSUE THREAD

**Issue by XinwenXiang** [yuchen1024/Kunlun#2]
hello,
I'm doing some scheme's implementation, i want to ask in your nizk folder "this hpp implements the merge of (relation R1 and R2) in ESORICS 2015" is which article?

**Comment by XinwenXiang** [comment]
it may be the [BCC+15]? ,if is [BCC+15],it may lack some part.
like in your accountable ring sig, you only count 
![image](https://user-images.githubusercontent.com/33709586/220240674-f6604997-a916-42c1-b16c-38bd847c7161.png)
it should alson include the 
![image](https://user-images.githubusercontent.com/33709586/220240738-c695aafe-b5f1-429c-8a30-e537cd759ed7.png)

**Comment by yuchen1024** [comment]
Thanks for your interest. 
Yes, ESORICS 2015  refers to "Short Accountable Ring Signatures Based on DDH". 
The implementation replaced ElGamal with twisted ElGamal. I cannot remember the details. I am not sure if this is the reason that the code is slight different from the protocol specified in the paper.

**Comment by XinwenXiang** [comment]
yeah, in your implementation you use twisted EIGamml, what is twisted ElGamal?
and I also want to ask: In R_sig proof to R2, R2 want prove that N ElGamal Ciphertexts has a ciphertext encrypt '1', but in your code, you find the signer index,but 
![image](https://user-images.githubusercontent.com/33709586/220275905-ac43c274-c03e-44e9-9968-c7412eb7fb8d.png)
but in [BCC+15] it really confused me
![image](https://user-images.githubusercontent.com/33709586/220275979-39bc4672-c9ca-4da9-8bc2-e65f49762f74.png)
(excuse me that our server has down last days, i can't run it
thanks for your answer.

**Comment by yuchen1024** [comment]
I did not implement the original ESORICS 2015 protocol, but implemented a new protocol case tailored for twisted ElGamal (perhaps with some tiny optimization trick, I cannot remember the details for the moment). 
You can find more details about Twisted ElGamal in https://eprint.iacr.org/2019/319
