### ISSUE TITLE
How to use curve25519？

### ISSUE THREAD

**Issue by ql70ql70** [yuchen1024/Kunlun#9]
I want to use curve25519, but when I modify "crypto/ec_group.hpp" line 16-18 from

`#define USING_CURVE_25519`
`inline int curve_id = NID_X9_62_prime256v1; `
to
`#define USING_CURVE_25519`
`//inline int curve_id = NID_X9_62_prime256v1; `

Then the project cannot be compiled successfully.

If I do not modify, the output "EC group info" shows that it uses X9_62_prime256v1.

**Comment by yuchen1024** [comment]
Thanks for this question. I have made the description of curve choices more clear. Please see the readme for details. In sum, curve25519 can only be used to improve EC exponentiation operations in some applications, and ordinary EC curve is always needed.

**Comment by ql70ql70** [comment]
Thank you for your patient explanation. I mistakenly thought that curve25519 can completely replace other ordinary EC curves for acceleration. It seems that I misunderstood.
